<?xml version="1.0"?>
<?xml-model
   href="http://download.ros.org/schema/package_format3.xsd"
   schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
 <name>bug_zapper_msgs</name>
 <version>0.0.0</version>
 <description>The Bug-Zapper messages package</description>
 <maintainer email="example@email.com">jdgre1</maintainer>
 <license>GNU General Public License</license>

  <depend>cv_bridge</depend>
  <depend>python3-opencv</depend>
  <depend>rclcpp</depend>
  <depend>rclcpp_lifecycle</depend>
  <depend>sensor_msgs</depend>
  <depend>std_msgs</depend>
  <depend>tf2_ros</depend>

<!-- <build_depend>rosidl_typesupport_cpp</build_depend> -->
<buildtool_depend>rosidl_default_generators</buildtool_depend>
<exec_depend>rosidl_default_runtime</exec_depend>
<!-- <exec_depend>rosidl_typesupport_cpp</exec_depend> -->
<member_of_group>rosidl_interface_packages</member_of_group>

 <export>
   <build_type>ament_cmake</build_type>
 </export>
</package>